# Generated by Django 5.2.4 on 2025-07-29 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='kategoriya nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='kategoriya nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Mahsulot kategoriyasi',
                'verbose_name_plural': 'Mahsulot kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='ProductTechnicalSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='nomi')),
                ('amount', models.CharField(max_length=200, verbose_name='miqdori')),
                ('type', models.CharField(choices=[('CHEMICAL_COMPOSITION', 'Kimyoviy Tarkib'), ('MECHANICAL_PROPERTIES', 'Mexanik Xususiyatlar'), ('PHYSICAL_PROPERTIES', 'Fizik Xususiyatlar'), ('PACKAGING_AND_STORAGE', 'Qadoqlash va Saqlash')], max_length=21, verbose_name='turi')),
            ],
            options={
                'verbose_name': 'Mahsulot texnik xususiyati',
                'verbose_name_plural': 'Mahsulot texnik xususiyati',
            },
        ),
        migrations.CreateModel(
            name='UsageArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='nom')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Soha',
                'verbose_name_plural': 'Sohalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='mahsulot nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='mahsulot nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='mahsulot nomi')),
                ('model', models.CharField(max_length=200, verbose_name='mahsulot modeli')),
                ('description', models.TextField(verbose_name='mahsulot haqida')),
                ('description_uz', models.TextField(null=True, verbose_name='mahsulot haqida')),
                ('description_ru', models.TextField(null=True, verbose_name='mahsulot haqida')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory', verbose_name='mahsulot kategoriyasi')),
                ('usage_area', models.ManyToManyField(related_name='products', to='products.usagearea', verbose_name="qo'llash sohalari")),
            ],
            options={
                'verbose_name': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='xususiyat')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='xususiyat')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='xususiyat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='products.product', verbose_name='mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot xususiyati',
                'verbose_name_plural': 'Mahsulot xususiyatlari',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ImageField(upload_to='product/product_media/', verbose_name='rasm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_medias', to='products.product', verbose_name='maxsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
            },
        ),
    ]
