# Generated by Django 5.2.4 on 2025-07-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttechnicalspecifications',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_tech_specifications', to='products.product'),
            preserve_default=False,
        ),
    ]
