# Generated by Django 5.2.4 on 2025-07-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttechnicalspecifications_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
