# Generated by Django 5.2.4 on 2025-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='mahsulot haqida'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='mahsulot nomi'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='xususiyat'),
        ),
        migrations.AddField(
            model_name='producttechnicalspecifications',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='usagearea',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='nom'),
        ),
    ]
