# Generated by Django 5.2.4 on 2025-07-29 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='sarlovha')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('banner', models.ImageField(upload_to='common/banner/')),
                ('page', models.CharField(choices=[('HOME', 'bosh sahifa'), ('ABOUT', 'biz haqimizda'), ('PRODUCTS', 'maxsulotlar'), ('CONTACT', "biz bilan bo'glanish")], max_length=50)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'bannerlar',
            },
        ),
    ]
