# Generated by Django 5.2.4 on 2025-07-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlovha'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlovha'),
        ),
    ]
