# Generated by Django 5.2.4 on 2025-07-29 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_banner_description_ru_banner_description_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_text', models.CharField(max_length=200, verbose_name='lokatsiya')),
                ('email', models.EmailField(max_length=254, verbose_name="elektron po'chta")),
                ('first_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='birinchi raqam')),
                ('second_phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='ikkinchi raqam')),
                ('facebook_url', models.URLField(verbose_name='facebook link')),
                ('instagram_url', models.URLField(verbose_name='instagram link')),
                ('telegram_url', models.URLField(verbose_name='telegram link')),
                ('youtube_url', models.URLField(verbose_name='youtube link')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
    ]
