# Generated by Django 5.2.4 on 2025-07-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='settings',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
