# Generated by Django 5.2.4 on 2025-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='text'),
        ),
    ]
