# Generated by Django 5.2.4 on 2025-07-29 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_aboutus_text_ru_aboutus_text_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year_expirence', models.CharField(max_length=20, verbose_name='Yillik tajriba')),
                ('happy_client', models.CharField(max_length=20, verbose_name='Mamnun mijozlar')),
                ('product_type', models.CharField(max_length=20, verbose_name='Maxsulot turi')),
                ('quality_assurance', models.CharField(max_length=20, verbose_name='Sifat kafolati')),
            ],
            options={
                'verbose_name': 'kompaniy statistikasi',
                'verbose_name_plural': 'kompaniy statistikasi',
            },
        ),
    ]
