# Generated by Django 5.2.4 on 2025-07-29 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sertificate', models.ImageField(upload_to='common/sertificate/')),
            ],
            options={
                'verbose_name': 'sertifikat',
                'verbose_name_plural': 'sertifikatlar',
            },
        ),
    ]
