# Generated by Django 5.2.4 on 2025-07-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_setificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setificate',
            new_name='Sertificate',
        ),
    ]
