# Generated by Django 5.2.4 on 2025-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_setificate_sertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificate',
            name='sertificate',
            field=models.ImageField(upload_to='common/sertificate/', verbose_name='sertifikat'),
        ),
    ]
