# Generated by Django 5.2.4 on 2025-07-29 12:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_sertificate_sertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='maxsulot nomi')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='maxsulot nomi')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='maxsulot nomi')),
                ('hs_code', models.CharField(max_length=200, verbose_name='hs kodi')),
            ],
            options={
                'verbose_name': 'maxsulotlar haqida',
            },
        ),
    ]
