# Generated by Django 5.2.4 on 2025-07-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_productinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'maxsulot haqida', 'verbose_name_plural': 'maxsulotlar haqida'},
        ),
    ]
