# Generated by Django 5.2.4 on 2025-07-29 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_productinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContactInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=15, null=True, verbose_name='birinchi telefon raqam')),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='ikkinchi telefon raqam')),
                ('phone_number_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='uchunchi telefon raqam')),
                ('email_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='birinchi email')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ikkinchi email')),
                ('email_3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='uchinchi email')),
                ('working_hours_monday_fridy', models.CharField(max_length=100, verbose_name='dushanbadan jumagacha ish soatlari')),
                ('working_hours_saturday', models.CharField(max_length=200, verbose_name='shanba kuni ish soatlari')),
                ('working_hours_sunday', models.CharField(blank=True, default='Yopiq', max_length=200, null=True, verbose_name='yakshanba kuni ish soatlari')),
                ('address', models.CharField(max_length=200, verbose_name='lokatsiya')),
            ],
            options={
                'verbose_name': "kompaniyaning aloqa ma'lumoti",
                'verbose_name_plural': "kompaniyaning aloqa ma'lumotlari",
            },
        ),
    ]
