# Generated by Django 5.2.4 on 2025-07-29 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_companycontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_contacted', models.BooleanField(default=False, verbose_name='aloqaga chiqilganmi')),
                ('full_name', models.CharField(max_length=100, verbose_name="to'liq ism sharif")),
                ('email', models.EmailField(max_length=254, verbose_name='elektron pochta')),
                ('phone_number', models.CharField(max_length=15, verbose_name='telefon raqam')),
                ('company_name', models.CharField(max_length=200, verbose_name='companiya nomi')),
                ('message', models.TextField(verbose_name='xabar')),
            ],
            options={
                'verbose_name': 'aloqa uchun xabar',
                'verbose_name_plural': 'aloqa uchun xabarlar',
            },
        ),
    ]
