# Generated by Django 5.2.4 on 2025-07-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('PRODUCT_INQUIRY', "mahsulot so'rovi"), ('TECHNICAL_SUPPORT', 'texnik yordam'), ('PARTNERSHIP', 'hamkorlik'), ('COMPLAINT', 'shikoyat'), ('OTHER', 'boshqa')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
