# Generated by Django 5.2.4 on 2025-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_contactus_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='happy_client',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='quality_assurance',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='year_expirence',
        ),
        migrations.AddField(
            model_name='statistics',
            name='count',
            field=models.CharField(default='', max_length=20, verbose_name='statistika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='statistika nomi'),
            preserve_default=False,
        ),
    ]
