# Generated by Django 5.2.4 on 2025-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_statistics_happy_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='statistika nomi'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='statistika nomi'),
        ),
    ]
