# Generated by Django 5.2.4 on 2025-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_statistics_name_ru_statistics_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.FileField(upload_to='common/banner/'),
        ),
    ]
