# Generated by Django 5.2.4 on 2025-08-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_banner_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
