# Generated by Django 5.2.4 on 2025-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_contactus_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.AddField(
            model_name='settings',
            name='first_email',
            field=models.EmailField(default='test@gmail.com', max_length=254, verbose_name="birinchi elektron po'chta"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='second_email',
            field=models.EmailField(default='test2@gmail.com', max_length=254, verbose_name="ikkinchi elektron po'chta"),
            preserve_default=False,
        ),
    ]
