# Generated by Django 5.2.4 on 2025-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_settings_email_settings_first_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='first_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='birinchi raqam'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='second_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ikkinchi raqam'),
        ),
    ]
