# Generated by Django 5.2.4 on 2025-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_alter_settings_first_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontactinfo',
            name='address_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='address_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
    ]
