# Generated by Django 5.2.4 on 2025-08-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_companycontactinfo_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_en',
            field=models.TextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='sarlovha'),
        ),
        migrations.AddField(
            model_name='companycontactinfo',
            name='address_en',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='maxsulot nomi'),
        ),
        migrations.AddField(
            model_name='settings',
            name='text_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='statistika nomi'),
        ),
    ]
