# Generated by Django 5.2.4 on 2025-08-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_aboutus_text_en_banner_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='location_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_text_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
        migrations.AddField(
            model_name='settings',
            name='location_text_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='lokatsiya'),
        ),
    ]
